/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.ui;

import de.fub.mapsforge.project.detector.model.Detector;
import de.fub.mapsforge.project.detector.model.pipeline.preprocessors.FilterProcess;
import de.fub.mapsforge.project.detector.model.process.AbstractDetectorProcess;
import de.fub.mapsforge.project.detector.model.process.DetectorProcess;
import de.fub.mapsforge.project.detector.model.xmls.ProcessDescriptor;
import de.fub.utilsmodule.Collections.ObservableList;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.Lookup;

/**
 *
 * @author Serdar
 */
public class PreprocessorComponent extends javax.swing.JPanel implements ChangeListener {

    private static final long serialVersionUID = 1L;
    private Detector detector;

    /**
     * Creates new form PreprocessorComponent
     */
    public PreprocessorComponent() {
        initComponents();
        selectionComponent1.getAllItemListTitle().setText("Registered Preprocessors"); //NO18N
        selectionComponent1.getSelectedItemListTitle().setText("Selected Preprocessors"); //NO18N
        ArrayList<FilterProcess> arrayList = new ArrayList<FilterProcess>(Lookup.getDefault().lookupResult(FilterProcess.class).allInstances());
        Collections.sort(arrayList);
        selectionComponent1.getAllItems().addAll(arrayList);
    }

    public PreprocessorComponent(Lookup lookup) {
        this();
        detector = lookup.lookup(Detector.class);
        assert detector != null;
        Collection<FilterProcess> processes = detector.getPreProcessorPipeline().getProcesses();
        selectionComponent1.getSelectedItems().addAll(processes);
        ObservableList<DetectorProcess> allItems = selectionComponent1.getAllItems();

        ArrayList<DetectorProcess> toRemoveItems = new ArrayList<DetectorProcess>();
        for (FilterProcess process : processes) {
            for (DetectorProcess detectorProcess : allItems) {
                if (process.getClass().equals(detectorProcess.getClass())) {
                    toRemoveItems.add(detectorProcess);
                }
            }
        }

        allItems.removeAll(toRemoveItems);
        selectionComponent1.getSelectedItems().addChangeListener(PreprocessorComponent.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionComponent1 = new de.fub.mapsforge.project.detector.ui.SelectionComponent();

        setLayout(new java.awt.BorderLayout());
        add(selectionComponent1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.fub.mapsforge.project.detector.ui.SelectionComponent selectionComponent1;
    // End of variables declaration//GEN-END:variables

    @Override
    public synchronized void stateChanged(ChangeEvent e) {

        List<ProcessDescriptor> preprocessorList = detector.getDetectorDescriptor().getPreprocessors().getPreprocessorList();

        preprocessorList.clear();

        for (DetectorProcess process : selectionComponent1.getSelectedItems()) {
            if (process instanceof AbstractDetectorProcess) {
                AbstractDetectorProcess abstractDetectorProcess = (AbstractDetectorProcess) process;
                preprocessorList.add(abstractDetectorProcess.getProcessDescriptor());
            }
        }

    }
}
