/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.plugins.tasks;

import de.fub.mapsforge.project.MapsForgeAggregatorHelper;
import de.fub.mapsforge.project.aggregator.filetype.AggregatorDataObject;
import de.fub.mapsforge.project.models.Aggregator;
import de.fub.utilsmodule.components.CustomOutlineView;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.Action;
import javax.swing.ListSelectionModel;
import org.openide.explorer.ExplorerManager;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;
import org.openide.loaders.DataObject;
import org.openide.loaders.DataObjectNotFoundException;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.ChildFactory;
import org.openide.nodes.Children;
import org.openide.nodes.FilterNode;
import org.openide.nodes.Node;
import org.openide.util.Exceptions;
import org.openide.util.WeakListeners;

/**
 *
 * @author Serdar
 */
public class AggregatorChooserPanel extends javax.swing.JPanel implements ExplorerManager.Provider, PropertyChangeListener {

    public static final String PROP_NAME_ACTIVE = "active";
    private static final long serialVersionUID = 1L;
    private final ExplorerManager explorerManager = new ExplorerManager();
    private final AggregatorDataObjectPropertyEditor propertyEditor;
    private boolean panelActive = false;
    private final PropertyChangeSupport pcs = new PropertyChangeSupport(this);

    /**
     * Creates new form AggregatorChooserPanel
     */
    public AggregatorChooserPanel(AggregatorDataObjectPropertyEditor propertyEditor) {
        assert propertyEditor != null;
        initComponents();
        this.propertyEditor = propertyEditor;
        init();
    }

    private void init() {
        outlineView1.getOutline().setRootVisible(false);
        outlineView1.getOutline().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        explorerManager.setRootContext(new AbstractNode(Children.create(new NodeFactory(), true)));
        Object value = propertyEditor.getValue();
        if (value instanceof AggregatorDataObject) {
            selectAggregator(((AggregatorDataObject) value));
        }
        explorerManager.addPropertyChangeListener(WeakListeners.propertyChange(AggregatorChooserPanel.this, explorerManager));
    }

    private void selectAggregator(AggregatorDataObject aggregatorDataObject) {
        Children children = explorerManager.getRootContext().getChildren();

        for (Node node : children.getNodes(true)) {
            Aggregator aggregator = node.getLookup().lookup(Aggregator.class);
            if (aggregator != null) {
                aggregator.getDataObject().equals(aggregatorDataObject);
                try {
                    explorerManager.setSelectedNodes(new Node[]{node});
                } catch (PropertyVetoException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        }
    }

    @Override
    public void addNotify() {
        super.addNotify();
        Object oldValue = panelActive;
        panelActive = true;
        pcs.firePropertyChange(PROP_NAME_ACTIVE, oldValue, panelActive);
    }

    @Override
    public void removeNotify() {
        Object oldValue = this.panelActive;
        panelActive = false;
        pcs.firePropertyChange(PROP_NAME_ACTIVE, oldValue, panelActive);
        super.removeNotify();
    }

    @Override
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        super.addPropertyChangeListener(listener);
        pcs.addPropertyChangeListener(listener);
    }

    @Override
    public void addPropertyChangeListener(String propertyName, PropertyChangeListener listener) {
        super.addPropertyChangeListener(propertyName, listener);
        pcs.addPropertyChangeListener(propertyName, listener);
    }

    @Override
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        super.removePropertyChangeListener(listener);
        pcs.removePropertyChangeListener(listener);
    }

    @Override
    public void removePropertyChangeListener(String propertyName, PropertyChangeListener listener) {
        super.removePropertyChangeListener(propertyName, listener);
        pcs.removePropertyChangeListener(propertyName, listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outlineView1 = new CustomOutlineView("Aggregators");

        setLayout(new java.awt.BorderLayout());
        add(outlineView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.OutlineView outlineView1;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (ExplorerManager.PROP_SELECTED_NODES.equals(evt.getPropertyName()) && panelActive) {
            Node[] selectedNodes = getExplorerManager().getSelectedNodes();
            if (selectedNodes.length == 1) {
                propertyEditor.setValue(selectedNodes[0].getLookup().lookup(DataObject.class));
            } else {
                propertyEditor.setValue(null);
            }
        }
    }

    private static class NodeFactory extends ChildFactory<AggregatorDataObject> {

        public NodeFactory() {
        }

        @Override
        protected boolean createKeys(List<AggregatorDataObject> toPopulate) {
            FileObject aggregatorTemplates = FileUtil.getConfigFile("Templates/Aggregators");
            if (aggregatorTemplates != null) {
                for (FileObject childFileObject : aggregatorTemplates.getChildren()) {
                    try {
                        DataObject childDataObject = DataObject.find(childFileObject);
                        if (childDataObject instanceof AggregatorDataObject) {
                            toPopulate.add(((AggregatorDataObject) childDataObject));
                        }
                    } catch (DataObjectNotFoundException ex) {
                        Exceptions.printStackTrace(ex);
                    }
                }
            }
            return true;
        }

        @Override
        protected Node createNodeForKey(AggregatorDataObject dataObject) {
            return new AggregatorFilterNode(dataObject.getNodeDelegate());
        }
    }

    private static class AggregatorFilterNode extends FilterNode {

        public AggregatorFilterNode(Node original) {
            super(original, org.openide.nodes.Children.LEAF);
        }

        @Override
        public PropertySet[] getPropertySets() {
            return new PropertySet[0];
        }

        @Override
        public Action[] getActions(boolean context) {
            return new Action[0];
        }
    }
}
