/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.gpx.analysis.ui;

import de.fub.gpxmodule.GPXDataObject;
import de.fub.gpxmodule.xml.Gpx;
import de.fub.mapsforge.gpx.analysis.models.GpxTrackSegmentStatistic;
import de.fub.mapsforge.gpx.analysis.models.nodes.GpxRootNode;
import java.awt.Image;
import java.beans.BeanInfo;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JToolBar;
import javax.swing.tree.TreeSelectionModel;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.UndoRedo;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.WeakListeners;
import org.openide.windows.TopComponent;

/**
 *
 * @author Serdar
 */
@MultiViewElement.Registration(
        displayName = "#LBL_GPX_ANALYSIS_VISUAL",
        //        iconBase = "de/fub/gpxmodule/gpx.png",
        mimeType = "text/gpx+xml",
        persistenceType = TopComponent.PERSISTENCE_NEVER,
        preferredID = "GPXAnalysisVisual",
        position = 550)
@NbBundle.Messages({"LBL_GPX_ANALYSIS_VISUAL=Analysis"})
public class GpxAnalysisVisualElement extends javax.swing.JPanel implements MultiViewElement, ExplorerManager.Provider, PropertyChangeListener {

    private static final long serialVersionUID = 1L;
    private GPXDataObject obj;
    private MultiViewElementCallback callback;
    private final JToolBar toolbar = new JToolBar();
    private final ExplorerManager explorerManager = new ExplorerManager();

    /**
     * Creates new form GpxAnalysisVisualElement
     */
    public GpxAnalysisVisualElement() {
        initComponents();
        beanTreeView1.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        explorerManager.addPropertyChangeListener(WeakListeners.propertyChange(GpxAnalysisVisualElement.this, explorerManager));
    }

    public GpxAnalysisVisualElement(Lookup lkp) {
        this();
        obj = lkp.lookup(GPXDataObject.class);
        assert obj != null;
        init();
    }

    private void init() {
        Gpx gpx = obj.getGpx();
        GpxRootNode gpxRootNode = new GpxRootNode(gpx);
        explorerManager.setRootContext(gpxRootNode);
    }

    @Override
    public String getName() {
        return "GPXAnalysisVisualElement";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();
        jPanel1 = new javax.swing.JPanel();
        gpxTrkSegAnalysizerTopComponent1 = new de.fub.mapsforge.gpx.analysis.ui.GpxTrkSegAnalysizerTopComponent();

        setLayout(new java.awt.BorderLayout());

        beanTreeView1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        beanTreeView1.setPreferredSize(new java.awt.Dimension(300, 400));
        beanTreeView1.setRootVisible(false);
        add(beanTreeView1, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(gpxTrkSegAnalysizerTopComponent1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    private de.fub.mapsforge.gpx.analysis.ui.GpxTrkSegAnalysizerTopComponent gpxTrkSegAnalysizerTopComponent1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComponent getVisualRepresentation() {
        return this;
    }

    @Override
    public JComponent getToolbarRepresentation() {
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return new Action[0];
    }

    @Override
    public Lookup getLookup() {
        return obj != null ? obj.getLookup() : Lookup.EMPTY;
    }

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    @Override
    public void componentShowing() {
    }

    @Override
    public void componentHidden() {
    }

    @Override
    public void componentActivated() {
    }

    @Override
    public void componentDeactivated() {
    }

    @Override
    public UndoRedo getUndoRedo() {
        return UndoRedo.NONE;
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback callback) {
        this.callback = callback;
        if (callback != null) {
            Image icon = obj.getNodeDelegate().getIcon(BeanInfo.ICON_COLOR_16x16);
            if (icon != null) {
                callback.getTopComponent().setIcon(icon);
            }
            callback.getTopComponent().setDisplayName(obj.getName());
        }
    }

    @Override
    public CloseOperationState canCloseElement() {
        return CloseOperationState.STATE_OK;
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (ExplorerManager.PROP_SELECTED_NODES.equals(evt.getPropertyName())) {
            Node[] selectedNodes = explorerManager.getSelectedNodes();
            GpxTrackSegmentStatistic statistic = null;

            if (selectedNodes.length == 1) {
                statistic = selectedNodes[0].getLookup().lookup(GpxTrackSegmentStatistic.class);
            }

            gpxTrkSegAnalysizerTopComponent1.setStatistic(statistic);

        }
    }
}
