/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.maps.project.detector.model.pipeline.postprocessors.tasks;

import de.fub.maps.project.detector.model.Detector;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;

/**
 *
 * @author Serdar
 */
public class DataAnalyzeTaskTopComponent extends TopComponent {

    private static final long serialVersionUID = 1L;
    private final Lookup lookup;
    private final DataAnalyzeTask task;

    public DataAnalyzeTaskTopComponent(DataAnalyzeTask task, Detector detector, Lookup lookup) {
        this.lookup = lookup;
        this.task = task;
        initComponents();
        setDisplayName(detector.getName());
        setToolTipText(this.task.getDescription());
        associateLookup(trainingDataAnalyizerComponent1.getLookup());
    }

    @Override
    protected void componentOpened() {
        super.componentOpened();
        trainingDataAnalyizerComponent1.componentOpened();
    }

    @Override
    protected void componentClosed() {
        super.componentClosed();
        trainingDataAnalyizerComponent1.componentClosed();
    }

    @Override
    protected void componentShowing() {
        super.componentShowing();
        trainingDataAnalyizerComponent1.componentShowing();
    }

    @Override
    protected void componentHidden() {
        super.componentHidden();
        trainingDataAnalyizerComponent1.componentHidden();
    }

    @Override
    protected void componentActivated() {
        super.componentActivated();
        trainingDataAnalyizerComponent1.componentActivated();
    }

    @Override
    protected void componentDeactivated() {
        super.componentDeactivated();
        trainingDataAnalyizerComponent1.componentDeactivated();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainingDataAnalyizerComponent1 = new de.fub.maps.project.detector.model.statistics.TrainingDataAnalyizerComponent(lookup);

        setLayout(new java.awt.BorderLayout());
        add(trainingDataAnalyizerComponent1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.fub.maps.project.detector.model.statistics.TrainingDataAnalyizerComponent trainingDataAnalyizerComponent1;
    // End of variables declaration//GEN-END:variables
}
