/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.wizards.detector;

import de.fub.mapsforge.project.detector.model.inference.features.FeatureProcess;
import de.fub.mapsforge.project.detector.model.process.DetectorProcess;
import de.fub.utilsmodule.Collections.ObservableList;
import javax.swing.JPanel;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

@NbBundle.Messages({
    "CLT_InferenceModelFeatures_Name=Features",
    "CLT_All_Features_Title=All Available Features",
    "CLT_Selected_Features_Title=Selected Features"
})
public final class InferenceModelFeatureSelectionVisualPanel extends JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form InferenceModelFeatureSelectionVisualPanel
     */
    public InferenceModelFeatureSelectionVisualPanel() {
        initComponents();
        getAllFeatures().addAll(Lookup.getDefault().lookupResult(FeatureProcess.class).allInstances());
        selectionComponent.getAllItemListTitle().setText(Bundle.CLT_All_Features_Title());
        selectionComponent.getSelectedItemListTitle().setText(Bundle.CLT_Selected_Features_Title());
    }

    @Override
    public String getName() {
        return Bundle.CLT_InferenceModelFeatures_Name();
    }

    public ObservableList<DetectorProcess> getAllFeatures() {
        return selectionComponent.getAllItems();
    }

    public ObservableList<DetectorProcess> getSelectedFeatures() {
        return selectionComponent.getSelectedItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionComponent = new de.fub.mapsforge.project.detector.ui.SelectionComponent();

        setPreferredSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.BorderLayout());
        add(selectionComponent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.fub.mapsforge.project.detector.ui.SelectionComponent selectionComponent;
    // End of variables declaration//GEN-END:variables
}
