/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.wizards.detector;

import de.fub.mapsforge.project.detector.model.pipeline.preprocessors.FilterProcess;
import de.fub.mapsforge.project.detector.model.process.DetectorProcess;
import de.fub.utilsmodule.Collections.ObservableList;
import javax.swing.JPanel;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

@NbBundle.Messages({
    "CLT_Preprocessors_Panel_Name=Preprocessors",
    "CLT_All_Available_Preprocessors=All Preprocessor Filters",
    "CLT_Selected_Preprocessors=Selected Preprocessor Filters"
})
public final class PreprocessorSelectionVisualPanel extends JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form PreprocessorSelectionVisualPanel
     */
    public PreprocessorSelectionVisualPanel() {
        initComponents();
        init();
    }

    private void init() {
        selectionComponent.getAllItemListTitle().setText(Bundle.CLT_All_Available_Preprocessors());
        selectionComponent.getSelectedItemListTitle().setText(Bundle.CLT_Selected_Preprocessors());
        getAllFilters().addAll(Lookup.getDefault().lookupResult(FilterProcess.class).allInstances());
    }

    public ObservableList<DetectorProcess> getAllFilters() {
        return selectionComponent.getAllItems();
    }

    public ObservableList<DetectorProcess> getSelectedFilters() {
        return selectionComponent.getSelectedItems();
    }

    @Override
    public String getName() {
        return Bundle.CLT_Preprocessors_Panel_Name();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionComponent = new de.fub.mapsforge.project.detector.ui.SelectionComponent();

        setLayout(new java.awt.BorderLayout());
        add(selectionComponent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.fub.mapsforge.project.detector.ui.SelectionComponent selectionComponent;
    // End of variables declaration//GEN-END:variables
}
