/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.wizards.detector;

import javax.swing.JPanel;

public final class PreprocessorSelectionVisualPanel4 extends JPanel {

    /**
     * Creates new form PreprocessorSelectionVisualPanel4
     */
    public PreprocessorSelectionVisualPanel4() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Step #4";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionComponent = new de.fub.mapsforge.project.detector.ui.SelectionComponent();

        setLayout(new java.awt.BorderLayout());
        add(selectionComponent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.fub.mapsforge.project.detector.ui.SelectionComponent selectionComponent;
    // End of variables declaration//GEN-END:variables
}
