/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.wizards.detector;

import de.fub.mapsforge.project.detector.model.xmls.TransportMode;
import de.fub.utilsmodule.Collections.ObservableArrayList;
import de.fub.utilsmodule.Collections.ObservableList;
import java.util.List;
import javax.swing.Action;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.ChildFactory;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;

@NbBundle.Messages({
    "CLT_TransportMode_And_Trainingset=Transport modes & Trainingsset"
})
public final class TrainingSetSelectionVisualPanel extends JPanel implements ExplorerManager.Provider, Lookup.Provider {

    private static final long serialVersionUID = 1L;
    private final ExplorerManager explorerManager = new ExplorerManager();
    private Lookup lookup = ExplorerUtils.createLookup(explorerManager, getActionMap());

    /**
     * Creates new form TrainingSetSelectionVisualPanel
     */
    public TrainingSetSelectionVisualPanel() {
        initComponents();
        beanTreeView1.setRootVisible(true);
        RootNode rootNode = new RootNode();
        getExplorerManager().setRootContext(rootNode);
    }

    @Override
    public String getName() {
        return Bundle.CLT_TransportMode_And_Trainingset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        setLayout(new java.awt.BorderLayout());

        beanTreeView1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        add(beanTreeView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerManager;
    }

    @Override
    public Lookup getLookup() {
        return lookup;
    }

    public static class RootNode extends AbstractNode {

        public static final String ACTION_PATH = "mapsforge/Detector/Wizard/Traningsset/Actions";
        private final ObservableList<String> transportModeNameList;
        private final InstanceContent content;

        public RootNode() {
            this(new ObservableArrayList<String>(), new InstanceContent());
        }

        private RootNode(ObservableList<String> transportModeNameList, InstanceContent content) {
            super(Children.create(new TransportNodeFactory(transportModeNameList), true), new AbstractLookup(content));
            setDisplayName("Transport Modes");
            this.transportModeNameList = transportModeNameList;
            this.content = content;
            this.content.add(RootNode.this);
        }

        @Override
        public Action[] getActions(boolean context) {
            List<? extends Action> actionsForPath = Utilities.actionsForPath(ACTION_PATH);
            return actionsForPath.toArray(new Action[actionsForPath.size()]);
        }

        public ObservableList<String> getTransportModeNameList() {
            return transportModeNameList;
        }
    }

    public static class TransportNodeFactory extends ChildFactory<String> implements ChangeListener {

        private final ObservableList<String> transportModeNameList;

        public TransportNodeFactory(ObservableList<String> transportModeNames) {
            this.transportModeNameList = transportModeNames;
            transportModeNames.addChangeListener(TransportNodeFactory.this);
        }

        @Override
        protected boolean createKeys(List<String> list) {
            list.addAll(transportModeNameList);
            return true;
        }

        @Override
        protected Node createNodeForKey(String transportModeName) {
            TransportMode transportMode = new TransportMode(transportModeName);
            return new TransportModeFilterNode(transportMode, transportModeNameList);
        }

        @Override
        public void stateChanged(ChangeEvent e) {
            refresh(true);
        }
    }

    public static class TransportModeFilterNode extends AbstractNode {

        public static final String ACTION_PATH = "mapsforge/Detector/Wizard/Traningsset/Transportmode/Actions";
        private final InstanceContent content;
        private final TransportMode transportMode;
        private final ObservableList<String> transportNodeNameList;

        public TransportModeFilterNode(TransportMode transportMode, ObservableList<String> transportModeNameList) {
            this(transportMode, transportModeNameList, new InstanceContent());
        }

        private TransportModeFilterNode(TransportMode transportMode, ObservableList<String> transportModeNameList, InstanceContent content) {
            super(Children.LEAF, new AbstractLookup(content));
            setDisplayName(transportMode.getName());
            this.content = content;
            this.content.add(TransportModeFilterNode.this);
            this.transportMode = transportMode;
            this.transportNodeNameList = transportModeNameList;
        }

        @Override
        public Action[] getActions(boolean context) {
            List<? extends Action> actionsForPath = Utilities.actionsForPath(ACTION_PATH);
            return actionsForPath.toArray(new Action[actionsForPath.size()]);
        }

        public TransportMode getTransportMode() {
            return transportMode;
        }

        public ObservableList<String> getTransportNodeNameList() {
            return transportNodeNameList;
        }
    }
}
