/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.model.statistics;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.labels.StandardXYItemLabelGenerator;
import org.jfree.chart.labels.StandardXYToolTipGenerator;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.StandardXYBarPainter;
import org.jfree.chart.renderer.xy.XYBarRenderer;
import org.jfree.data.statistics.HistogramDataset;

/**
 *
 * @author Serdar
 */
public class HistogramPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private final HistogramDataset dataSet = new HistogramDataset(); // NO18N
    private final JFreeChart histogramChart;
    private final XYPlot plot;
    private final ChartPanel chartPanel;

    /**
     * Creates new form histogramPanel
     */
    public HistogramPanel() {
        initComponents();
        histogramChart = ChartFactory.createHistogram(null, null, null, dataSet, PlotOrientation.VERTICAL, false, true, true);
        plot = histogramChart.getXYPlot();
        chartPanel = new ChartPanel(histogramChart, true);
        add(chartPanel, BorderLayout.CENTER);
        XYBarRenderer barRenderer = new XYBarRenderer(.05);
        barRenderer.setBaseToolTipGenerator(new StandardXYToolTipGenerator());
        barRenderer.setBarPainter(new StandardXYBarPainter());
        barRenderer.setBarAlignmentFactor(.1);
        barRenderer.setBasePaint(Color.blue);
        barRenderer.setBaseItemLabelGenerator(new StandardXYItemLabelGenerator());
        barRenderer.setBaseItemLabelsVisible(true);
        plot.setRenderer(barRenderer);
        plot.setBackgroundPaint(Color.white);
        histogramChart.setBackgroundPaint(Color.white);
        plot.setRangeGridlinesVisible(true);
        chartPanel.setVerticalAxisTrace(false);
        chartPanel.setDisplayToolTips(true);
        chartPanel.setBackground(Color.white);
    }

    public HistogramDataset getDataSet() {
        return dataSet;
    }

    public JFreeChart getHistogramChart() {
        return histogramChart;
    }

    public XYPlot getPlot() {
        return plot;
    }

    public ChartPanel getChartPanel() {
        return chartPanel;
    }

    public ValueAxis getDomainAxis() {
        return plot.getDomainAxis();
    }

    public ValueAxis getRangeAxis() {
        return plot.getRangeAxis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
