/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.fub.mapsforge.project.detector.model.inference.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Serdar
 */
public class BarChartPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private final ChartPanel chartPanel;
    private DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    private final JFreeChart barChart;
    private final CategoryPlot plot;

    /**
     * Creates new form BarChartPanel
     */
    public BarChartPanel() {
        super();
        initComponents();
        barChart = ChartFactory.createBarChart(null, "Transport Modes", "Precision (%)", dataset, PlotOrientation.VERTICAL, true, true, true);
        plot = barChart.getCategoryPlot();
        plot.setBackgroundPaint(Color.white);
        chartPanel = new ChartPanel(barChart, true);
        chartPanel.setVerticalAxisTrace(false);
        add(chartPanel, BorderLayout.CENTER);
    }

    public ChartPanel getChartPanel() {
        return chartPanel;
    }

    public DefaultCategoryDataset getDataset() {
        return dataset;
    }

    public JFreeChart getBarChart() {
        return barChart;
    }

    public CategoryPlot getPlot() {
        return plot;
    }

    public void setTitle(TextTitle title) {
        barChart.setTitle(title);
    }

    public CategoryAxis getDomainAxis() {
        return plot.getDomainAxis();
    }

    public ValueAxis getRangeAxis() {
        return plot.getRangeAxis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
